# Generated by Django 3.1.3 on 2021-01-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201011_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='layout',
            field=models.CharField(choices=[('FL', 'Full-width container'), ('CM', 'Centered 7-size column')], default='FL', max_length=2),
        ),
    ]
