# Generated by Django 3.1.5 on 2021-01-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_contentpage_article_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='article_image_caption',
            field=models.TextField(blank=True, null=True, verbose_name='Article image caption (only for blog)'),
        ),
    ]
