# Generated by Django 3.1 on 2020-08-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200828_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='geolocation',
        ),
    ]
