# Generated by Django 3.1 on 2020-09-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200828_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
