# Generated by Django 3.1.1 on 2020-09-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200901_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('string', models.TextField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
