# Generated by Django 3.1.1 on 2020-09-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_phrase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='count',
        ),
        migrations.AddField(
            model_name='phrase',
            name='incidents',
            field=models.ManyToManyField(to='main.Incident'),
        ),
    ]
