# Generated by Django 3.1.1 on 2020-09-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200902_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='incidents',
        ),
        migrations.AddField(
            model_name='phrase',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
