# Generated by Django 3.1.1 on 2020-09-03 08:46

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200902_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
