# Generated by Django 3.1.1 on 2020-09-03 09:30

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_incident_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
