# Generated by Django 3.1.1 on 2020-09-08 08:29

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_trigram_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geolocation_geometry',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
