# Generated by Django 3.1.1 on 2020-09-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_location_geolocation_geometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='string',
            new_name='option',
        ),
    ]
