# Generated by Django 3.1.1 on 2020-09-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200909_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='subdivisions',
            new_name='location_string',
        ),
    ]
