# Generated by Django 3.1.1 on 2020-09-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200911_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='subdivision',
            new_name='subdivisions',
        ),
    ]
