# Generated by Django 3.1.1 on 2020-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200916_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='phrases',
            field=models.ManyToManyField(to='main.Phrase'),
        ),
    ]
