# Generated by Django 3.1.1 on 2020-09-18 15:19

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_incident_phrases'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
