# Generated by Django 3.1.1 on 2020-09-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200927_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='orig_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='orig_county',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
