# Generated by Django 3.1.3 on 2021-01-02 17:08

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200927_1646'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='incident',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_incide_search__d9b3b8_gin'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_locati_search__bfc501_gin'),
        ),
        migrations.AddIndex(
            model_name='phrase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_phrase_search__d7ceb4_gin'),
        ),
    ]
