# Generated by Django 3.1.5 on 2021-01-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210102_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='orig_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
