# Generated by Django 3.1.5 on 2021-01-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210123_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rg_id',
            field=models.CharField(max_length=255),
        ),
    ]
