# Generated by Django 3.1.5 on 2021-01-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210123_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
