# Generated by Django 3.1.5 on 2021-01-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210123_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
