# Generated by Django 3.1.5 on 2021-01-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_incidentsubmitted"),
    ]

    operations = [
        migrations.DeleteModel(name="IncidentSubmitted"),
    ]
