# Generated by Django 3.1.5 on 2021-01-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_delete_incidentsubmitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSubmitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_input', models.TextField()),
                ('sources_input', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rg_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('contexts', models.TextField(blank=True, null=True)),
                ('factums', models.TextField(blank=True, null=True)),
                ('motives', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
