# Generated by Django 3.1.5 on 2021-01-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_incidentsubmitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_id', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
