# Generated by Django 3.1.5 on 2021-02-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsubmitted',
            name='email',
            field=models.EmailField(blank=True, help_text='Lass uns deine E-Mail Adresse da, damit wir mit dir bei Nachfragen in Kontakt treten können.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
