# Generated by Django 3.1.5 on 2021-02-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210207_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='description',
            field=models.TextField(help_text="Erzähl in ein paar Sätzen, worum es geht. Z. B. 'In der XY Schule ist eine unbekannte Person dabei beobachtet worden, wie sie ....'", verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='email',
            field=models.EmailField(blank=True, help_text='Lass uns optional deine E-Mail Adresse da, damit wir mit dir bei Nachfragen in Kontakt treten können.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='location_input',
            field=models.TextField(help_text="Z. B. 'Dortmund, Dorstfeld'", verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='sources_input',
            field=models.TextField(help_text='Schick uns öffentliche Belege zu, für den von dir geschilderten Fall. Z. B. Links zu einem Zeitungsbericht.', verbose_name='Quellen'),
        ),
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='title',
            field=models.CharField(help_text="Beschreib in ein paar Worten, was passiert ist. Z. B. 'Hakenkreuz an Schulwand gesprüht'", max_length=1000, verbose_name='Titel'),
        ),
    ]
