# Generated by Django 3.1.5 on 2021-02-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210207_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentsubmitted',
            name='location_input',
            field=models.CharField(help_text="Z. B. 'Dortmund, Dorstfeld'", max_length=1000, verbose_name='Ort'),
        ),
    ]
