# Generated by Django 3.1.5 on 2021-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210207_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorreport',
            name='rg_id',
        ),
        migrations.AddField(
            model_name='errorreport',
            name='email',
            field=models.EmailField(blank=True, help_text='Lass uns optional deine E-Mail Adresse da, damit wir mit dir bei Nachfragen in Kontakt treten können.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='incident_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='description',
            field=models.TextField(help_text='Bitte beschreib deinen Fehler.', verbose_name='Beschreibung'),
        ),
    ]
