# Generated by Django 3.1.5 on 2021-02-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210207_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='incident_id',
            field=models.IntegerField(null=True),
        ),
    ]
