# Generated by Django 3.1.5 on 2021-02-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210208_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorreport',
            name='incident_id',
        ),
        migrations.AddField(
            model_name='errorreport',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.incident'),
        ),
    ]
